---
- name: Test connectivity
  hosts: poc_hosts
  become: true

  tasks:
    # Test connectivity to host & store it in a register & print out result
    - name: Test connectivity to host
      ansible.builtin.ping:

    - name: Store it in a register
      ansible.builtin.set_fact:
        ping_result: "{{ ansible_ping }}"

    - name: Print out result
      ansible.builtin.debug:
        msg: "{{ ping_result }}"
    
    
    
