---
- name: Add tasks to playbooks
  hosts: poc_hosts
  become: true

  tasks:
  - name: copy files from PoC1 to PoC3
  ansible.builtin.copy:
    src: /home/PoC1/   
    dest: /home/PoC3/

  - name: copy files from PoC2 to PoC3
  ansible.builtin.copy:
    src: /home/PoC2/   
    dest: /home/PoC3/
