---
- name: AWS EC2 VM
  hosts: poc_hosts
  become: true

  tasks:
  - name: provision aws instance
    amazon.aws.ec2_instance:
      region: us-east-2
      key_name: "{{ _key_name_ }}"
      instance_type: t2.micro
      image_id: ami-05fa00d4c63e32376
      wait: true
      count: 1
      vpc_subnet_id: subnet-0a59730f37c77bc4f
      security_group: elk_security_group
      network:
        assign_public_ip: true
      tags:
        Environment: Dev
        Attempt: MyAttempting
        Role: RDS
        Site: "{{ site }}"
    register: ec2
  
  - name: Provision an AWS EC2 VM
    amazon.aws.ec2_instance:
      access_key: "{{ access_key }}"
      secret_key: "{{ aws_secret_key }}"
      key_name: "{{ ssh_key_name }}"
      instance_type: "{{ aws_instance_type }}"
      image_id: "{{ aws_image_id }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ aws_vpc }}"
      security_group: "{{ aws_security_group }}"
      cpu_options:
        core_count: 2
        threads_per_core: 2
      network:
        assign_public_ip: true
      tags:
        tag1: poc
        tag2: ansible
      name: ansible-poc-aws
      state: present
  
  - name: take snapshot of ec2 instance
    amazon.aws.ec2_snapshot:
      volume_id: "{{ aws_volume_id }}"
      region: "{{ aws_region }}"
      description: ansible-poc-snapshot
  
